apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "acme.fullname" . }}
  labels: {{ include "acme.labels.standard" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
