apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acme.fullname" . }}
  labels: {{ include "acme.labels.standard" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "acme.fullname" . }}
  labels: {{ include "acme.labels.standard" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "acme.fullname" . }}
  labels: {{ include "acme.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "acme.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "acme.fullname" . }}
  namespace: {{ .Release.Namespace }}
