{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acme.fullname" . }}
  labels: {{ include "acme.labels.standard" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
