apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-gateway.fullname" . }}
  labels:
    {{- include "minio-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ .Values.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.rootPassword | quote }}
