{{- if not .Values.rootUser.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-gateway.rootUser.secretName" . }}
  labels:
    {{- include "minio-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "minio-gateway.rootUser.secretUserKey" . }}: {{ .Values.rootUser.user | quote }}
  {{ include "minio-gateway.rootUser.secretPasswordKey" . }}: {{ .Values.rootUser.password | quote }}
{{- end }}
