apiVersion: v1
kind: Service
metadata:
  name: {{ include "reverse-proxy.fullname" . }}
  labels:
    {{- include "reverse-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalName: {{ .Values.service.externalName }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: portsecure
  selector:
    {{- include "reverse-proxy.selectorLabels" . | nindent 4 }}
