{
 "title": "Logs / Overview",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Errors for platform Namespace",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"platform\", app=~\"platform-(api|auth|apps(-v2)?|billing|poller|monitoring|payments|config|metadata|secrets|service-accounts|service-versions|registry|storage.*|neuro-flow|notifications).*\"} |~ \"(?i)(error|exception)\" | json | line_format \"{{._entry}}\"\n"
    }
   ]
  },
  {
   "title": "Errors for apolo* & app* Namespaces",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{namespace=~\"apolo.*|app.*\", app=~\".+\"} |~ \"(?i)(error|exception)\" | json | line_format \"{{._entry}}\" \n"
    }
   ]
  },
  {
   "title": "Full Logs for all Namespaces",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "{namespace=~\".+\", app=~\".+\"} | json | line_format \"{{._entry}}\""
    }
   ]
  }
 ]
}