{
 "title": "Platform-Uptime",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Running Platform internal Services",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"annotated_ping\"} == 1",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Running Platform external Services",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"external_https_ping\"} == 1",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Down Platform external Services",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_success{job=\"external_https_ping\"} == 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Down Platform internal Services",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_success{job=\"annotated_ping\"} == 0",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}