{
 "title": "Status / Codes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "5xx Errors",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(probe_http_status_code[5m]) >= 500",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "4xx Errors",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(probe_http_status_code[5m]) >= 400\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "3xx Errors",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(probe_http_status_code[5m]) >= 300",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(probe_http_status_code[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}