{
 "title": "Uptime / Service",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "target",
    "query": {
     "query": "label_values(probe_success,target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last 3 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{target=\"$target\"}[3h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{target=\"$target\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 7d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{target=\"$target\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{target=\"$target\"}[$__interval]) * 100",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{target=\"$target\"}",
     "legendFormat": "Time"
    }
   ]
  }
 ]
}