{
 "title": "Uptime / Panels",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Last 3 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(probe_success[3h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(probe_success[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last 7d",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (avg_over_time(probe_success[7d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst 20 Endpoints",
   "type": "status-history",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bottomk(20,\n  label_replace(\n    avg_over_time(probe_success[$__interval]),\n    \"instance\", \"$1\", \"instance\", \"https?://([^/]+).*\"\n  ) * 100\n)\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Currently Failing",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "label_replace(\n  max_over_time(probe_success[5m]) == 0,\n  \"domain\", \"$1\", \"target\", \"https?://([^/]+).*\"\n)\n\n\n\n\n",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Best 20 Endpoints",
   "type": "state-timeline",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "topk(20,\n  avg by (domain) (\n    label_replace(probe_success, \"domain\", \"$1\", \"target\", \"https?://([^/]+).*\")\n  ) * 100\n)\n",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}