{
 "title": "Uptime / Internal-Public",
 "time": { "from": "2025-06-15T20:09:05.039Z", "to": "2025-06-15T20:13:11.748Z" },
 "panels": [
  {
   "title": "Running Internal Services (platform)",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{job=~\"apis_.*\"}) == 1",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Down Internal Services (platform)",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (service) (probe_success{job=~\"apis_.*\", service!=\"platform-ingress-fallback\"}) == 0",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Running Public Endpoints (platform)",
   "type": "state-timeline",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{job=\"public_endpoints\", namespace=\"platform\"}) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Public Endpoints (platform)",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{job=\"public_endpoints\", namespace=\"platform\"}) == 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Public Endpoints",
   "type": "state-timeline",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{job=\"public_endpoints\"}) == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Down Public Endpoints",
   "type": "state-timeline",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "max by (target) (probe_success{job=\"public_endpoints\"}) == 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}