{{- if .Values.minioConfig.observabilityBucket.create }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-create-minio-bucket
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: create-bucket
        image: minio/mc:latest  # Using MinIO Client image
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minioConfig.secretName }}  # Secret name from values.yaml
              key: {{ .Values.minioConfig.accessKeyField }}  # Key name in the secret for access key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.minioConfig.secretName }}  # Secret name from values.yaml
              key: {{ .Values.minioConfig.secretKeyField }}
        - name: MINIO_ENDPOINT
          value: {{ .Values.minioConfig.endpoint }}
        - name: MINIO_BUCKET_NAME
          value: {{ .Values.minioConfig.observabilityBucket.name }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          # Create MinIO config
          mc alias set myminio ${MINIO_ENDPOINT} ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          # Create the bucket
          mc mb myminio/${MINIO_BUCKET_NAME} || echo "Bucket already exists."
      restartPolicy: OnFailure
{{- end }}
