apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-db-init.fullname" . }}
  labels: {{ include "postgres-db-init.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ .Values.hook }}
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": {{ .Values.hookWeight | default -1 | quote }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: postgres-db-init
          configMap:
            name: {{ include "postgres-db-init.fullname" . }}
            defaultMode: 0777
      {{- if .Values.migrations.enabled }}
      initContainers:
      {{- else }}
      containers:
      {{- end }}
        - name: init-db
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: [/var/lib/postgres_db_init/init_db.sh]
          volumeMounts:
            - name: postgres-db-init
              mountPath: /var/lib/postgres_db_init
          env:
          {{- with .Values.extensions }}
            - name: NP_POSTGRES_EXTENSIONS
              value: {{ . | join " " | quote }}
          {{- end }}
          {{- with .Values.adminDsn }}
            - name: NP_ADMIN_DSN
{{ toYaml . | indent 14 }}
          {{- end }}
          {{- with .Values.migrationsRunnerDsn }}
            - name: NP_MIGRATIONS_RUNNER_DSN
{{ toYaml . | indent 14 }}
          {{- end }}
          {{- with .Values.serviceDsn }}
            - name: NP_SERVICE_DSN
{{ toYaml . | indent 14 }}
          {{- end }}
          {{- with .Values.env }}
{{ toYaml . | indent 12 }}
          {{- end }}
      {{- if .Values.migrations.enabled }}
      containers:
        - name: run-migrations
          image: {{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}
          imagePullPolicy: {{ .Values.migrations.imagePullPolicy }}
          {{- with .Values.migrations.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
