apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-db-init.fullname" . }}
  labels: {{ include "postgres-db-init.labels.standard" . | nindent 4 }}
  annotations:
    "helm.sh/hook": {{ .Values.hook }}
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": {{ .Values.hookWeight | default -1 | quote }}
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: postgres-db-init
          configMap:
            name: {{ include "postgres-db-init.fullname" . }}
            defaultMode: 0777
      {{- if .Values.migrations.enabled }}
      initContainers:
      {{- else }}
      containers:
      {{- end }}
        - name: create-users
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: [/var/lib/postgres_db_init/init_db.sh]
          volumeMounts:
            - name: postgres-db-init
              mountPath: /var/lib/postgres_db_init
          {{- if .Values.env }}
          env: {{ toYaml .Values.env | nindent 12 }}
          {{- end }}
          {{- if .Values.imagePullSecrets }}
          env: {{ toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
      {{- if .Values.migrations.enabled }}
      containers:
        - name: run-migrations
          image: {{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}
          {{- with .Values.migrations.command }}
          command: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.args }}
          args: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.migrations.env }}
          env: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.migrations.imagePullSecrets }}
          imagePullSecrets: {{ toYaml .Values.migrations.imagePullSecrets | nindent 12 }}
          {{- end }}
      {{- end }}
