{{- if .Values.additionalGrafanaDataSources.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-prometheus-datasource
  labels:
    loki-datasource: "enabled"
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: {{ .Values.additionalGrafanaDataSources.prometheus.url }}
      access: proxy
      isDefault: false
      editable: true
{{- end }}



