{{- if and .Values.secrets (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solution-agent-orchestrator.fullname" . }}-secret
  labels:
    {{- include "solution-agent-orchestrator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}

