apiVersion: v2
version: 1.2.0
appVersion: 1.2.0
name: postgres-db-init
description: PostgreSQL DB initialization
dependencies:
- name: postgres-db-init-script
  version: 1.0.0
  repository: https://neuro-inc.github.io/helm-charts
