image:
  repository: bitnami/postgresql
  tag: 11.14.0-debian-10-r17

hook: pre-install,pre-upgrade
hookWeight: -1

schema: public

env: []
# - name: NP_SCHEMA
#   value: public
# - name: NP_ADMIN_DSN
#   value: dsn
# - name: NP_MIGRATIONS_RUNNER_DSN
#   value: dsn
# - name: NP_SERVICE_DSN
#   value: dsn

adminDsn: {}
migrationsRunnerDsn: {}
serviceDsn: {}

migrations:
  enabled: false

  image:
    repository:
    tag:

  command: []
  args: []

  env: []
  imagePullSecrets: []

secret: {}
