image:
  repository: bitnami/postgresql
  tag: 11.14.0-debian-10-r17

imagePullSecrets: []

hook: pre-install,pre-upgrade
hookWeight: -1

extensions: []

schema: public

adminDsn: {}
migrationsRunnerDsn: {}
serviceDsn: {}

env: []
# - name: NP_POSTGRES_SCHEMA
#   value: public
# - name: NP_ADMIN_DSN
#   value: dsn
# - name: NP_MIGRATIONS_RUNNER_DSN
#   value: dsn
# - name: NP_SERVICE_DSN
#   value: dsn

migrations:
  enabled: false

  image:
    repository:
    tag:

  command: []
  args: []

  env: []

secret: {}
